import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import Header from "@/_components/Header"
import {
	ColorSchemeScript,
	MantineProvider,
	mantineHtmlProps,
} from "@mantine/core"
import "@mantine/core/styles.css"
import Footer from "@/_components/Footer"

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
})

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
})

export const metadata: Metadata = {
	title: "L.M. Store",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" {...mantineHtmlProps} suppressHydrationWarning={true}>
			<head>
				<ColorSchemeScript />
			</head>
			<body
				className={`${geistSans.variable} ${geistMono.variable} relative antialiased h-full w-full box-border m-0 p-0`}
			>
				<MantineProvider defaultColorScheme="light">
					<Header />
					{children}
					<Footer />
				</MantineProvider>
			</body>
		</html>
	)
}
